### PING Server
GET http://localhost:3001/ping_server

###  Create SKI Resort
POST http://localhost:3001/create_resort
Content-Type: application/json

{
    "name":"Group 3 SKI Resort 2",
    "status":true,
    "details":"lorem ipsum...."
}


###  add skill level
POST http://localhost:3001/add_skill_level
Content-Type: application/json

{
    "name":"Intermediate",
    "description":"lorem ipsum level 2"
}


###  Create Skier
POST http://localhost:3001/create_skier
Content-Type: application/json

{
    "name":"Jude Bellingham",
    "age":55,
    "skillLevel":"65f7b6cb37ca6ad818761f62",
    "status":true
}

###  Create Facility
POST http://localhost:3001/create_facility
Content-Type: application/json

{
    "name":"Open Source Restaurant 2",
    "facilityType":"X", 
    "description":"Assorted noodles maker...",
    "status":true
}

###  Get Facilities
GET http://localhost:3001/get_facilities



###  test run
POST http://localhost:3001/submit-data
Content-Type: application/json

{
    "type":"find_route",
    "data":{
        "from":"1",
        "to":"2"
    }
}


###  test run
POST http://localhost:3001/submit-data
Content-Type: application/json

{
    "type":"find_facilities"
}


###  test run
POST http://localhost:3001/submit-data
Content-Type: application/json

{
    "type":"get_routes"
}

###  test run
POST http://localhost:3001/submit-data
Content-Type: application/json

{
    "type":"find_routes"
}


###  test run
POST http://localhost:3001/submit-data
Content-Type: application/json

{
    "type":"add_nodes",
    "data":{
        "name":"Ski Node 1",
        "icon_name":"example image 1",
        "status":true,
        "location":{
            "type": "Point",
            "coordinates": [-0.0000545, 5.09209323]
        }
    }
}



###  test run

POST http://localhost:3001/submit-data
Content-Type: application/json

{
    "type":"add_routes",
    "data":{  
        "route_type":"slope",
        "fromNode": "65f9b451d3f604153d1d9b63",
        "toNode": "65f9b470d3f604153d1d9b65",
        "color": "green"
    }
}


###  test run
POST http://localhost:3001/submit-data
Content-Type: application/json

{
    "type":"get_nodes",
    "data":{  
        "fromNode": "65f9b40bd3f604153d1d9b5f",
        "toNode": "65f9b5b5d3f604153d1d9b6d"
    }
}

###  test run
POST http://localhost:3001/submit-data
Content-Type: application/json

{
    "type":"search_route"
}

###  test run
POST http://localhost:3001/submit-data
Content-Type: application/json

{
    "type":"get_lifts"
}



###  test run
POST http://localhost:3001/submit-data
Content-Type: application/json

{
    "type":"get_slopes"
}




